DROP TABLE IF EXISTS EMPLEADOS;
DROP TABLE IF EXISTS  CENTROS;

CREATE TABLE CENTROS (
    NUM_CENTRO INT PRIMARY KEY,
    NOMBRE_CENTRO VARCHAR(100)
);

-- Crear la tabla EMPLEADOS
CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    ID_CENTRO INT,
    FOREIGN KEY (ID_CENTRO) REFERENCES CENTROS(NUM_CENTRO)
);


